### ISSUE TITLE
Minor version number may contain non numbers

### ISSUE THREAD

**Issue by va1ha11a** [kvaps/kubectl-node-shell#15]
When running ` kubectl version --client -o yaml` I get the following output:
```
clientVersion:
  buildDate: "2020-01-15T08:26:26Z"
  compiler: gc
  gitCommit: e7f962ba86f4ce7033828210ca3556393c377bcc
  gitTreeState: clean
  gitVersion: v1.16.6-beta.0
  goVersion: go1.13.5
  major: "1"
  minor: 16+
  platform: linux/amd64
```

The minor: 16+ breaks the check for minor version

I will add a pull request that filters non numerical from the minor version string shortly.
